source "https://rubygems.org"

gem "berkshelf",  ">= 4.3.3"
gem "chef", ">= 12.10.24"
gem "chefspec",   ">= 4.7.0"
gem "foodcritic", ">= 6.3.0"
gem "github_changelog_generator"
gem "kitchen-appbundle-updater", ">= 0.1.2"
gem "kitchen-docker", ">= 2.4.0"
gem "kitchen-vagrant", ">= 0.20.0"
gem "knife-spork"
gem "lcgstyle"
gem "rake"
gem "stove", ">= 4.0.0"
gem "test-kitchen", ">= 1.8.0"
gem "tomlrb"
